### ISSUE TITLE
offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.

### ISSUE THREAD

**Issue by fallingmeteorite** [deepghs/imgutils#112]
When I set the environment variable HF_HUB_OFFLINE=1,
The code doesn't load the local model, it throws an exception, but when I use other features, it loads the local model
I confirm that the model is cached locally
![fd2e5342128b8d9b346043ca07c6564d](https://github.com/user-attachments/assets/d82eee64-ac7d-4f70-8fbb-7b9b693520ea)

![2dd219d175a1126e31bb4cfba632fbda](https://github.com/user-attachments/assets/666ce3d3-2478-4705-861f-3381f3abf0d7)

The error occurred in anime_face_detection model
However, ccip-caformer-24-randaug-pruned  model does not report an error when loaded
Environment:
dghs-imgutils Version: 0.6.0

**Comment by fallingmeteorite** [comment]
I've found a similar issue:https://github.com/huggingface/optimum/issues/1796

**Comment by narugo1992** [comment]
well, this is highly probably to be an issue of huggingface_hub, not dghs-imgutils.

**Comment by fallingmeteorite** [comment]
@narugo1992  This is indeed a bug
But the problem is with from huggingface_hub import HfFileSystem, hf_hub_download
At the moment I only found it in this file https://github.com/deepghs/imgutils/blob/main/imgutils/generic/yolo.py
I found a solution,https://github.com/huggingface/huggingface_hub/issues/2590
Maybe you can use it before calling this function and prevent the exception from happening
I'll submit an example of a change later, but I'm not sure that all the places that contain the call will change

**Comment by fallingmeteorite** [comment]
@narugo1992 https://github.com/deepghs/imgutils/pull/115

**Comment by fallingmeteorite** [comment]
![e3097f70c614c77e66e9121559231bc6](https://github.com/user-attachments/assets/7ef3e9d2-738f-4b91-b728-e499e91746f8)
Before fixing

![47faf0962a7de11e82ed413f68c76f3d](https://github.com/user-attachments/assets/b0ed7fd6-b4d9-4b7f-a573-7f5a811d690f)
After the fix
